name: 'Send a test report to Telegram'
description: 'Sends test reports to a Telegram Bot'
inputs:
  telegram_bot_token:
    description: 'The token for the Telegram bot'
    required: true
  telegram_chat_id:
    description: 'The chat ID to send messages to'
    required: true
  report_file:
    description: 'Path to the report file to send'
    required: true
  message:
    description: 'Message to include with the report'
    required: false
    default: 'Test report'

runs:
  using: 'node20'
  main: 'index.js'
  steps: 
    - name: 'Install dependencies' 
      run: npm install
 
branding:
  icon: check-square
  color: purple
